# The book's title. Will be used everywhere!
title: "Upgrading to Rails 4"

# The book's language.
language: en

# Your book copyright info.
# Here's some examples:
#
#   Copyright 2012 by Andy Lindeman.
#   Copyright 2012 by Andy Lindeman. This work is licensed under MIT License.
#   This work is licensed under a Creative Commons Attribution-ShareAlike 3.0 Unported License.
#   This work is licensed under a Creative Commons Attribution-NonCommercial-NoDerivs 3.0 Unported License.
#   This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License.
#
copyright: "Copyright (C) 2012-2013 Andy Lindeman. Licensed under CC BY 3.0."

# Who's publishing this book.
publisher: "Andy Lindeman"

# When this book was published.
published_at: "2012-10-27"

# Some book description.
subject: "A guide for upgrading applications from Rails 3 to Rails 4"

# Some keywords that identify this book.
keywords: "rails4, rails, ruby, web"

# Some unique identification. Works great with your domain
# like `http://yourbook.example.com`.
uid: "http://upgradingtorails4.com"

# Your book identification like ISBN or ISSN.
identifier:
  id: "http://upgradingtorails4.com"
  type: "URL" # can be ISBN, ISSN or URL

# This book authors.
authors:
  - "Andy Lindeman"

# The base URL from your source code.
base_url: https://github.com/alindeman/upgradingtorails4
