# The book's title. Will be used everywhere!
title: "[Your Book Title]"

# The book's language.
language: en

# Your book copyright info.
# Here's some examples:
#
#   Copyright 2012 by Andy Lindeman.
#   Copyright 2012 by Andy Lindeman. This work is licensed under MIT License.
#   This work is licensed under a Creative Commons Attribution-ShareAlike 3.0 Unported License.
#   This work is licensed under a Creative Commons Attribution-NonCommercial-NoDerivs 3.0 Unported License.
#   This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License.
#
copyright: "Copyright (C) 2012 Andy Lindeman."

# Who's publishing this book.
publisher: "Andy Lindeman"

# When this book was published.
published_at: "2012-10-27"

# Some book description.
subject: "[Your book description]"

# Some keywords that identify this book.
keywords: "[Your book keywords (comma-separated)]"

# Some unique identification. Works great with your domain
# like `http://yourbook.example.com`.
uid: "5c1a4510c6a8e9404ef36aa4fa910c9c"

# Your book identification like ISBN or ISSN.
identifier:
  id: "http://yourbook.example.com"
  type: "URL" # can be ISBN, ISSN or URL

# This book authors.
authors:
  - "Andy Lindeman"

# The base URL from your source code.
base_url: http://example.com
